###############################################################################
# MODULE.bazel
# Purpose: Bazel build rules for configuring ECUs using DaVinci Configurator Classic Version 6.
# Author: Vector Informatik GmbH
###############################################################################
bazel_dep(name = "rules_cfg6", version = "2.0.1")
bazel_dep(name = "dvcfg6", version = "6.2.5")

# Import the BSW package as a local repository.
bsw_pkg = use_repo_rule("//build-starter:helpers.bzl", "bsw_pkg")
bsw_pkg(
    name = "bsw_package",
    # Provide the path to the BSW package folder.
    path = "D:/dev/dvcfg-test-workspaces/davinci/bswPackage",
)

# Include build-starter projects.
include("//build-starter/com-diag:com-diag.MODULE.bazel")
include("//build-starter/eac:eac.MODULE.bazel")
include("//build-starter/project-creation:project-creation.MODULE.bazel")
